ANS 1:

In [1]:
import numpy as np

# creating a array using numpy arange
arr = np.arange(2, 50, 3)

# printing array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


ANS 2:

In [2]:
import numpy as np

# creating a 2 empty list:
lst_1 = []
lst_2 = []

# getting values for lst_1 from user:
for i in range(5):
  x=int(input("\nEnter the value for lst_1 : "))
  lst_1.append(x)

# getting values for lst_2 from user:
for i in range(5):
  x=int(input("\nEnter the value for lst_2 : "))
  lst_2.append(x)

# converting list into array:
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

# concatenating 2 array:
arr = np.concatenate((arr_1, arr_2))
print("\nArray value for concatenated arr :",arr)

# sorting up concatenated array
sortArr = np.sort(arr)
print("\nSorted Array for concatenated arr :",sortArr)


Enter the value for lst_1 : 3

Enter the value for lst_1 : 2

Enter the value for lst_1 : 5

Enter the value for lst_1 : 4

Enter the value for lst_1 : 6

Enter the value for lst_2 : 1

Enter the value for lst_2 : 0

Enter the value for lst_2 : 7

Enter the value for lst_2 : 9

Enter the value for lst_2 : 8

Array value for concatenated arr : [3 2 5 4 6 1 0 7 9 8]

Sorted Array for concatenated arr : [0 1 2 3 4 5 6 7 8 9]


ANS 3:

In [3]:
import numpy as np

# creating a 2d array
arr = np.array([[1,2,3],[1,3,5]])

# Printing array dimensions (axes)
print("\nDimensions in array : ", arr.ndim)
 
# Printing size of array
print("\nSize of array : ", arr.size)


Dimensions in array :  2

Size of array :  6


ANS 4:

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

# by adding new axis
arr1 = arr[np.newaxis, :]
print(arr1.shape)

# by expanding dimension
arr2 = np.expand_dims(arr, axis=1)
print(arr2.shape)

(6,)
(1, 6)
(6, 1)


ANS 5:

In [5]:
import numpy as np

# creating a array with square values
arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])

# stacking and printing the value
print("\nHorizontal Append :", np.hstack((arr_1, arr_2)))
print("Vertical Append :\n", np.vstack((arr_1, arr_2)))


Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]
Vertical Append :
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


ANS 6:

In [10]:
import numpy as np

# creating a array 
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True)

# making a 
arr = np.asarray((unique, counts))

print(arr)

[[ 1  2  3  4  5  6  7  8  9 10 16 25]
 [ 2  2  1  2  2  1  1  1  1  1  1  1]]
